- hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Create Deployment
    command: sudo kubectl create deployment medicure --image=minimalkushal/medicure
  - name: Expose Medicure Project
    command: sudo kubectl expose deployment medicure --type=NodePort --port=8082 --name=medicure-svc
  - name: Port Forward
    command: sudo kubectl port-forward service/medicure-svc 8082:8082
  - name: Get Services
    command: sudo kubectl get svc
